inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

inherit_from:
  - ".rubocop_todo.yml"

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - "test/**/*"
    - "tmp/**/*"
    - "activerecord.rake"

RSpec/NestedGroups:
  Max: 4

Style/ExtraSpacing:
  Exclude:
    - "activerecord-turntable.gemspec"

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SpaceAroundOperators:
  Exclude:
    - "activerecord-turntable.gemspec"
